### ISSUE TITLE
Missing networkAccess Field

### ISSUE THREAD

**Issue by akbarbmirza** [gabrielrbarbosa/figma-to-bootstrap-plugin#1]
Hey @gabrielrbarbosa - it looks like your plugin doesn't make any network requests (skimmed the codebase) - is that correct?. It's currently listed as Unknown Network Access on it's Figma Community Page. You can specify what kind of network access your plugin requires using instructions from the docs here: https://www.figma.com/plugin-docs/making-network-requests/#specify-network-access

By defining access to necessary domains, you can increase trust among security-conscious users and organization admins. **This is especially important for organizations that require admin approval for plugins/widget.**

If it doesn't make any network requests, you can add the following snippet as a field in your manifest and then it will list as No network access. 

```json
"networkAccess": {
    "allowedDomains": ["none"]
}
```

**Comment by gabrielrbarbosa** [comment]
It only calls bootstrap external CDN link to generate the HTML snippets, will this affect it or not?

**Comment by gabrielrbarbosa** [comment]
@akbarbmirza this is the only link used: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"

**Comment by akbarbmirza** [comment]
You'll want to specify the domain like in the example in the docs. This way folks using your plugin will see where the request is being made. It's in step 2. You can also provide reasoning for why you need it. Both of those will be visible to your users.
